### ISSUE TITLE
vuetify alpha 11/12

### ISSUE THREAD

**Issue by maschenborn** [peshanghiwa/Vue3-Vite-Vuetify3-Typescript-Template#2]
In Vuetify alpha 11/12 some things have changed
https://newreleases.io/project/github/vuetifyjs/vuetify/release/v3.0.0-alpha.11
I don't get it to work with this template.

**Comment by peshanghiwa** [comment]
> In Vuetify alpha 11/12 some things have changed https://newreleases.io/project/github/vuetifyjs/vuetify/release/v3.0.0-alpha.11 I don't get it to work with this template.

Can you please clarify exactly what are the THINGS that have changed and has made it not working on your side?
