### ISSUE TITLE
Question : what means "exports.colors"

### ISSUE THREAD

**Issue by ChristianRiedl** [peshanghiwa/Vue3-Vite-Vuetify3-Typescript-Template#4]
Sorry, I am not able to find out what means **exports.colors** in your mixin _computedMixins.ts_. Cany you please explain it ?

**Comment by peshanghiwa** [comment]
Mixins are just a way to distribute reusable scripts among vue components, it is now replaced with **composables** in vue 3, check it's [documentation](https://vuejs.org/guide/reusability/composables.html) to know more about it.

As of exports.colors, it's just an exmple object that i wrote which can be shared among the components, nothing more special about it.

Hope it helps
