### ISSUE TITLE
Any plans to incorporate pinia?

### ISSUE THREAD

**Issue by robinzimmermann** [peshanghiwa/Vue3-Vite-Vuetify3-Typescript-Template#8]
Excellent template, thank you!

Wondering if you'll convert from vuex to pinia....

**Comment by Liquidream** [comment]
I too would be very interested in this!
(+thx for awesome template)

**Comment by peshanghiwa** [comment]
I have just published a very new template that includes integration of (Pinia and Tailwind) and many more vue 3 related features,
Check it out here:
[Vue3-Vite-Pinia-Tailwind-Typescript-Template](https://github.com/peshanghiwa/Vue3-Vite-Pinia-Tailwind-Typescript-Template)

Thanks for the suggestion
